### ISSUE TITLE
Backup feature (Future)

### ISSUE THREAD

**Issue by reecepbcups** [Reecepbcups/minecraft-panel#6]
use scp & allow to define in the config to make backups

# hetzner storage box, make sure to do ssh key
```
backups:
  # 0 0 * * * python3 /home/craft/server/console.py backup-server
  uri: u999999@u999999.your-storagebox.de:/home/daily_backups/
  port: 23
  mongoDB: true
  exclude:
  - "*.zip"
  - 
```

```bash
cd /location/to/servers

# Feb-22-2022
filename="craft-network-$(date +%h-%d-%Y_%H-%M).zip"

zip -r ${filename} ./ -x "*cache/*" "*logs/*" "*crash-reports/*" "*aper-1.*.jar" "*node_modules/*" "*REST-API/dist/*" "*libraries/*" "*LuckPerms/libs/*" "*LuckPerms/translations/*" "*FastAsyncWorldEdit/history/*" "*MARKETING/*" "*WorldEdit/.archive-unpack/*"

# (where -x is in the exclude array from config.yml)

scp -P 23 $filename u999999@u999999.your-storagebox.de:/home/daily_backups/
rm $filename
rm -r /home/craft/server/CraftEconomy-MongoDB/

echo "Backup sent to 'u999999@u999999.your-storagebox.de:/home/daily_backups/'"
```
